p8105_hw3_xl3214
================
Xuan Lu
2023-10-11

## Question 1

``` r
library(dplyr)
library(ggplot2)
library(tidyverse)
library(p8105.datasets)
data("instacart")
head(instacart)
summary(instacart)
```

The **instacart** dataset has 1384617 observations and 15 variables,
including:

- `order_id`: order identifier, class integer.

- `product_id`: product identifier, class integer.

- `add_to_cart_order`: order in which each product was added to cart,
  class integer.

- `reordered`: 1 if this prodcut has been ordered by this user in the
  past, 0 otherwise, class integer.

- `user_id`: customer identifier, class integer.

- `eval_set`: which evaluation set this order belongs in (Note that the
  data for use in this class is exclusively from the “train” eval_set),
  class character.

- `order_number`: the order sequence number for this user (1=first,
  n=nth), class integer.

- `order_dow`: the day of the week on which the order was placed, class
  integer.

- `order_hour_of_day`: the hour of the day on which the order was
  placed, class integer.

- `days_since_prior_order`: days since the last order, capped at 30, NA
  if order_number=1, class integer.

- `product_name`: name of the product, class character.

- `aisle_id`: aisle identifier, class integer.

- `department_id`: department identifier, class integer.

- `aisle`: the name of the aisle, class character.

- `department`: the name of the department, class character.

<!-- -->

    ## # A tibble: 7 × 2
    ##   order_dow  n_obs
    ##       <int>  <int>
    ## 1         0 324026
    ## 2         1 205978
    ## 3         2 160562
    ## 4         3 154381
    ## 5         4 155481
    ## 6         5 176910
    ## 7         6 207279

- There are 131209 unique users and 131209 unique orders. On average,
  there are 1.9780243^{5} items sold per day. There are 134 aisles and
  21 departments. Below are some graphs to help visualize the dataset
  key variables.

![](p8105_hw3_xl3214_files/figure-gfm/Q1-%20Some%20basic%20visualizations-1.png)<!-- -->![](p8105_hw3_xl3214_files/figure-gfm/Q1-%20Some%20basic%20visualizations-2.png)<!-- -->![](p8105_hw3_xl3214_files/figure-gfm/Q1-%20Some%20basic%20visualizations-3.png)<!-- -->![](p8105_hw3_xl3214_files/figure-gfm/Q1-%20Some%20basic%20visualizations-4.png)<!-- -->

1.  How many aisles are there, and which aisles are the most items
    ordered from?

- Answer: There are 134 aisles, and most items are ordered from aisle
  *fresh vegetables*.

2.  Make a plot that shows the number of items ordered in each aisle,
    limiting this to aisles with more than 10000 items ordered. Arrange
    aisles sensibly, and organize your plot so others can read it.

![](p8105_hw3_xl3214_files/figure-gfm/Q1-%20Making%20the%20aisle%20plot-1.png)<!-- -->

- There are 39 aisles with more than 10,000 items ordered.

- Most aisles have less than 40,000 items ordered. There are 5 aisles
  that have more than 40,000 items sold. They are: fresh fruits, fresh
  vegetables, packaged cheese, packaged vegetables fruits, yogurt.

3.  Make a table showing the three most popular items in each of the
    aisles “baking ingredients”, “dog food care”, and “packaged
    vegetables fruits”. Include the number of times each item is ordered
    in your table.

<!-- -->

    ## # A tibble: 9 × 3
    ## # Groups:   aisle [3]
    ##   aisle                      product_name                                  n_obs
    ##   <chr>                      <chr>                                         <int>
    ## 1 packaged vegetables fruits Organic Baby Spinach                           9784
    ## 2 packaged vegetables fruits Organic Raspberries                            5546
    ## 3 packaged vegetables fruits Organic Blueberries                            4966
    ## 4 baking ingredients         Light Brown Sugar                               499
    ## 5 baking ingredients         Pure Baking Soda                                387
    ## 6 baking ingredients         Cane Sugar                                      336
    ## 7 dog food care              Snack Sticks Chicken & Rice Recipe Dog Treats    30
    ## 8 dog food care              Organix Chicken & Brown Rice Recipe              28
    ## 9 dog food care              Small Dog Biscuits                               26

- For aisle *packaged vegetables fruits*, products Organic Baby Spinach,
  Organic Raspberries, Organic Blueberries are the three most popular
  products, each correspond to 9784, 5546, 4966 in sales.

- For aisle *baking ingredients*, products Light Brown Sugar, Pure
  Baking Soda, Cane Sugar are the three most popular products, each
  correspond to 499, 387, 336 in sales.

- For aisle *dog food care*, products Snack Sticks Chicken & Rice Recipe
  Dog Treats, Organix Chicken & Brown Rice Recipe, Small Dog Biscuits
  are the three most popular products, each correspond to 30, 28, 26 in
  sales.

- Among the three aisles, Organic Baby Spinach has the most sales of
  9784.

4.  Make a table showing the mean hour of the day at which Pink Lady
    Apples and Coffee Ice Cream are ordered on each day of the week;
    format this table for human readers (i.e. produce a 2 x 7 table).

<!-- -->

    ## # A tibble: 1 × 7
    ##     Sun   Mon   Tue   Wed Thurs   Fri   Sat
    ##   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
    ## 1  13.6  12.2  12.8  14.7  13.2  12.6  13.2

- Wed has the latest mean hour of day at which Pink Lady Apples and
  Coffee Ice Cream are ordered.

## Question 2

``` r
data("brfss_smart2010")
```

``` r
#format the data to use appropriate variable names
#focus on the “Overall Health” topic, include only responses from “Excellent” to “Poor”
#organize responses as a factor taking levels ordered from “Poor” to “Excellent”
brfss <- brfss_smart2010 |>
  janitor::clean_names() |> 
  filter(topic == "Overall Health" & response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) |> 
  mutate(response = factor(response, 
                           levels=c("Poor", "Fair", "Good", "Very good", "Excellent"), ordered=TRUE)) |>
  rename(resp_id = respid, location_abbr = locationabbr, location_desc = locationdesc)
head(brfss)
unique(pull(brfss, topic))
unique(pull(brfss, response))
```

The BRFSS dataset has 10625 observations and 23 variables. Variables
include: year, location_abbr, location_desc, class, topic, question,
response, sample_size, data_value, confidence_limit_low,
confidence_limit_high, display_order, data_value_unit, data_value_type,
data_value_footnote_symbol, data_value_footnote, data_source, class_id,
topic_id, location_id, question_id, resp_id, geo_location.

1.  In 2002, which states were observed at 7 or more locations? What
    about in 2010?

- In 2002, MA, NJ, PA states were observed at 7 or more locations.

- In 2010, CA, FL, MA, MD, NC, NE, NJ, NY, OH, TX, WA states were
  observed at 7 or more locations.

2.  Construct a dataset that is limited to Excellent responses, and
    contains, year, state, and a variable that averages the data_value
    across locations within a state. Make a “spaghetti” plot of this
    average value over time within a state (that is, make a plot showing
    a line for each state across years – the geom_line geometry and
    group aesthetic will help).

<!-- -->

    ## # A tibble: 443 × 3
    ## # Groups:   year, location_abbr [443]
    ##     year location_abbr data_value_state_avg
    ##    <int> <chr>                        <dbl>
    ##  1  2010 AL                            18.4
    ##  2  2010 AZ                            21.6
    ##  3  2010 AR                            25.4
    ##  4  2010 CA                            23.9
    ##  5  2010 CO                            25.4
    ##  6  2010 CT                            24.2
    ##  7  2010 DE                            20.3
    ##  8  2010 DC                            26.1
    ##  9  2010 FL                            NA  
    ## 10  2010 GA                            23.1
    ## # ℹ 433 more rows

![](p8105_hw3_xl3214_files/figure-gfm/Q2-%20Spaghetti%20Plot-1.png)<!-- -->

- The average data values across locations within a state fluctuates
  across years, but overall remains fairly stable. There is no
  distinguishable trend in the average data values across years.

- Among all data available, UT in 2002 has the highest average data
  value, WV in 2005 has the lowest average data value.

3.  Make a two-panel plot showing, for the years 2006, and 2010,
    distribution of data_value for responses (“Poor” to “Excellent”)
    among locations in NY State.

![](p8105_hw3_xl3214_files/figure-gfm/Q2-%20Two-panel%20plot-1.png)<!-- -->![](p8105_hw3_xl3214_files/figure-gfm/Q2-%20Two-panel%20plot-2.png)<!-- -->

- Based on the plots, we can see that *Poor* responses correspond to the
  lowest data values across all locations in NY State for both 2006 and
  2010, and as the order of responses increases towards *Very good*, the
  data values also increase. However, for responses of *Excellent*, we
  see a decreased data value distribution compared to the previous
  *Good* and *Very good*.

- We can see that in 2006, responses *Good* and *Very good* have
  comparable data value distributions, although the median for *Very
  good* is slightly higher. When it comes to 2010, the data value for
  responses *Very good* is apparently higher than that of *Good*.
  Responses *Fair* and *Poor* in 2010 have wider spread compared to that
  of 2006.

## Question 3
